[package]
name = "fake_user_agent"
version = "0.1.0"
edition = "2021"
authors = ["Vraj Shah"]
description = "A fake user agent generator for Rust"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastrand = "1.9.0"
